name: FTP Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - "methods/PHPMailer/*"
      - "methods/fpdf/*"

jobs:

  # ==========================================
  # HOSTING PRINCIPAL
  # ==========================================
  ftp-deploy-principal:
    name: 🚀 Deploy to FTP server principal
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📤 FTP Deploy Principal
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}


  # ==========================================
  # HOSTING DE RESPALDO
  # ==========================================
  ftp-deploy-respaldo:
    name: 🚀 Deploy to FTP server respaldo
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📤 FTP Deploy Respaldo
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_BACKUP }}
          username: ${{ secrets.FTP_USERNAME_BACKUP }}
          password: ${{ secrets.FTP_PASSWORD_BACKUP }}
