name: FTP Deploy

on:
  push:
    branches:
      - main  # Cambia a la rama que quieras usar para desplegar
    paths-ignore:    
        - "PHPMailer/*" # Exclude everything in dist folder
        - "fpdf/*" # Exclude everything in dist folder

jobs:
  ftp-deploy:
    name: 🚀 Deploy to FTP server
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📤 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
